    version: '3.8'
    services:
      sftp-server:
        image: atmoz/sftp
        ports:
          - "2222:22"
        volumes:
          - sftp_data:/home/user
        environment:
          SFTP_USERS: "user:password:1001"
        
    volumes:
      sftp_data: